### ISSUE TITLE
Issues with multiple ips in x-forwarded-for and logging change

### ISSUE THREAD

**Issue by deepakdeore2004** [shukob/evasive#3]
It doesn't block the ip if there are multiple ip addresses in x-forwarded-for header.

Also can the logging be changed to log x-forwarded-for ip instead of load balancer's ip if DOSXForwardedForAsRemoteIP is set to 1 ?

Eg. In below log client ip is being printed as load balancer's ip, where if i have  then it should print ip address of x-forwarded-for because i have "DOSXForwardedForAsRemoteIP 1"

[Tue Sep 29 01:01:04 2015] [error] [client 10.2.0.130] client denied by server configuration: proxy:http://localhost:8080/some/file.js

**Comment by shukob** [comment]
Hi,

thank you for the suggestion.

In https://github.com/skonb/evasive/commit/ec61b2f4e3cafa374466f1a6182fd36dce370baa, extracting remote IP from X-Forwarded-For is thought to be implemented, so would you please check the branch?

For logging, if logging remote IP itself is required, instead of logging X-Forwarded-For as is, e.g 'IP1, IP2, ....', then this will make the logging as you expected.

Thank you

**Comment by deepakdeore2004** [comment]
Appreciate the quick reply :-)
